# Use an official Python runtime as a parent image
FROM public.ecr.aws/lambda/python:3.8

# Copy the dependencies file to the working directory
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY app_lambda.py ${LAMBDA_TASK_ROOT}

CMD ["app_lambda.handler"]
