AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for a Python Flask Lambda function.

Resources:
  FlaskLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 30
      Events:
        SlackEvent:
          Type: Api
          Properties:
            Path: /slack/events
            Method: post
        SlackCommand:
          Type: Api
          Properties:
            Path: /slack/commands
            Method: post
        SlackInteractive:
          Type: Api
          Properties:
            Path: /slack/interactive
            Method: post
        HelloRoute:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  APIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

